### PR TITLE
Added data module and code to get all estimators

### PR DESCRIPTION
**Pull request by yrahul3910**
This PR adds a data-loading module. It also adds a couple of utility functions to get all estimators with all kwargs combinations for our experiments.

### CODE REVIEW

**Comment by yrahul3910** [comment]
Not quite sure why it says the imports are unsorted. It seems to work locally (as much as I hate saying that). Can you pull the branch and check @Dref360? I'm not sure if it's a CI config issue or my local Ruff issue.

**Comment by yrahul3910** [comment]
Actually I think I see it. I wonder why my local ruff doesn't seem to work right.

**Comment by yrahul3910** [comment]
pre-commit.ci autofix

**Comment by yrahul3910** [comment]
pre-commit.ci autofix

**Review by Dref360 — APPROVED** [review]

**Pull request merged**
